### ISSUE TITLE
Column 'longitude' cannot be null

### ISSUE THREAD

**Issue by jyhsu2000** [vongola12324/sacard#4]
以表單placeholder作為測試資料輸入

> 分店名稱：逢甲店
> 分店地址：台中市北區文華路100號

提交表單後，出現以下錯誤

> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'longitude' cannot be null (SQL: insert into `positions` (`shop_id`, `description`, `address`, `longitude`, `latitude`, `updated_at`, `created_at`) values (1, 逢甲店, 台中市北區文華路100號, , , 2016-08-06 17:53:56, 2016-08-06 17:53:56))

初步猜測是嘗試利用`LocationService::getLocation`取得經緯度座標時未順利取得
（已確認直接透過瀏覽器開啟API網址，可順利取得資料JSON）

![screenshot_20160807_020125](https://cloud.githubusercontent.com/assets/6276648/17458442/ee05bc1e-5c42-11e6-9eae-e9721a9528a0.png)

**Comment by vongola12324** [comment]
經測試，我這邊測試，不管是用Browser Key還是Server Key都可以正確地抓到座標資料喔！

@jyhsu2000 請確定你的API Key有辦法存取Google Geocoding API。

**Comment by jyhsu2000** [comment]
看來整個想錯方向了
跟API Key無關
以下是找錯流程...

我先試著用`dd($url)`把`LocationService::getLocation($address)`的以下這行弄出來

``` php
$url = 'https://maps.googleapis.com/maps/api/geocode/json?address=' . trim($address) . '&key=' . env('GOOGLE_API_SERVER_KEY');
```

得到

```
https://maps.googleapis.com/maps/api/geocode/json?address=%E5%8F%B0%E4%B8%AD%E5%B8%82%E8%A5%BF%E5%B1%AF%E5%8D%80%E6%96%87%E5%8C%96%E8%B7%AF100%E8%99%9F&key=AIzaSyBSRWOSUSd░░░░░░░░░░owjwhCsezo
```

再拿得到的網址去瀏覽器試
兩組KEY分別得到以下兩張圖

![screenshot_20160807_180205](https://cloud.githubusercontent.com/assets/6276648/17461751/85166adc-5cc9-11e6-8c50-abb5f115a99a.png)

![screenshot_20160807_180142](https://cloud.githubusercontent.com/assets/6276648/17461752/8a3681be-5cc9-11e6-9237-390785473516.png)

從瀏覽器得到的回應看起來都有順利取得資料
且Google API Console資訊主頁的API請求次數有確實增加

後來又做了嘗試
- 去除網址的API Key
- 不同電腦
- 不同IP區段
- 不同地點
- 不同瀏覽器

仍可以順利取得API回應
看起來這API似乎不太在意Key

重新回到程式碼檢查

``` php
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_URL, $url);
$resp_json = curl_exec($ch);
```

逐行修改並倒出來看
一開始`$ch`有順利初始化，並且兩次`curl_setopt`皆設置成功
最後`curl_exec($ch)`雖有順利改動`$ch`的內容，但回傳是`FALSE`
意指CURL請求失敗
於是利用`dd(curl_error($ch));`將錯誤訊息印出
得到以下訊息

```
SSL certificate problem: unable to get local issuer certificate
```

可用的暫時解法
利用以下設定關閉憑證檢查

``` php
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
```

看要不要如此處理
或是有什麼解法吧

**Comment by jyhsu2000** [comment]
PS. 儘管更新到最新的 af038dac8c9eafaa4783de164215d34900ef19ff
依然會失敗
不過會從錯誤頁面
變成null
![screenshot_20160807_182949](https://cloud.githubusercontent.com/assets/6276648/17461876/0215d0b0-5ccd-11e6-8db9-016cb205afcc.png)
